In [1]:
import numpy as np
import pandas as pd
from sklearn.datasets import make_regression

In [2]:
X, y = make_regression(n_samples=100, n_features=10, noise=80, random_state=42)

In [3]:
from sklearn.linear_model import LinearRegression

In [4]:
lr = LinearRegression()

In [5]:
lr.fit(X, y)

LinearRegression()

In [6]:
lr.coef_

array([30.33423542, 63.52992344, -5.09101588, 58.25084505, 91.04001829,
       65.08066895, 74.54153815, -0.39155062,  7.55460004, 69.71564595])

In [7]:
lr.intercept_

10.45683454747535

In [128]:
class BatchGD:
    def __init__(self, learning_rate, epochs):
        self.coef_ = None
        self.intercept_ = 0
        self.lr = learning_rate
        self.epochs = epochs

    def fit(self, X, y):
        no_of_columns = X.shape[1]
        self.coef_ = np.ones(no_of_columns)
        slope_for_beta_i = np.zeros(no_of_columns)
        slope_for_beta_o = 0
        for i in range(self.epochs):
            y_pred = (self.coef_ @ X.T) + self.intercept_
            slope_for_beta_o = (-2/no_of_columns) * np.sum(y - y_pred)
            for i in range(no_of_columns):
                slope_for_beta_i[i] = (-2/no_of_columns) * np.sum((y - y_pred) @ X.T[i])
                self.coef_[i] = self.coef_[i] - (self.lr * slope_for_beta_i[i])
            self.intercept_ = self.intercept_ - (self.lr * slope_for_beta_o)
        return self.coef_, self.intercept_ #only for confirmation purpose
            
    def predict(self, X):
        return ((self.coef_ @ X.T) + self.intercept_)

In [129]:
gd = BatchGD(0.01, 100)

In [130]:
gd.fit(X, y)

(array([30.33427858, 63.53060013, -5.09183282, 58.25088627, 91.03933167,
        65.08164487, 74.54048757, -0.39267462,  7.55489174, 69.71445118]),
 10.456622337711897)

In [131]:
lr.coef_

array([30.33423542, 63.52992344, -5.09101588, 58.25084505, 91.04001829,
       65.08066895, 74.54153815, -0.39155062,  7.55460004, 69.71564595])

In [132]:
lr.intercept_

10.45683454747535